import re

with open('src/data/trade-markets.ts', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace(
    "| 'uae' | 'saudi-arabia' | 'iran' | 'russia' | 'china' | 'vietnam' | 'india';",
    "| 'uae' | 'saudi-arabia' | 'iran' | 'russia' | 'china' | 'vietnam' | 'india'\n  | 'albania' | 'serbia' | 'macedonia';"
)
content = content.replace(
    "'uae', 'saudi-arabia', 'iran', 'russia', 'china', 'vietnam', 'india'",
    "'uae', 'saudi-arabia', 'iran', 'russia', 'china', 'vietnam', 'india',\n  'albania', 'serbia', 'macedonia'"
)

balkans = {
    'tr': """    'albania': { slug: 'arnavutluk', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Arnavutluk Pazarı: Güvenilir Tedarik ve Lojistik.', description: 'Arnavutluk pazarına yönelik yapı malzemeleri, gıda ve endüstriyel ürünlerde kesintisiz tedarik zinciri.', lead: 'Arnavutluk\\'taki projelere ve toptancılara Türkiye üzerinden stratejik ürün tedariki sağlıyoruz.', heading2: 'Tiran ve Tüm Arnavutluk İçin Doğrudan Çözümler', body2: 'Mesafe avantajını kullanarak Arnavutluk pazarına esnek, hızlı ve güvenilir B2B ihracat operasyonları yönetiyoruz.', cta: 'Arnavutluk Tedarik Teklifi Al' },
    'serbia': { slug: 'sirbistan', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Sırbistan Pazarı: B2B İhracat ve Ticari Koordinasyon.', description: 'Sırbistan için Türkiye\\'den sanayi hammaddesi, cam ve gıda tedariki.', lead: 'Belgrad ve çevresindeki üretim tesislerine ve ithalatçılara Türkiye\\'den yüksek standartlı stratejik tedarik çözümleri sunuyoruz.', heading2: 'Sırbistan Sanayisi İçin Güçlü Köprü', body2: 'Sırbistan pazarına girmek isteyen üreticiler ile Sırbistan\\'daki alıcıları verimli bir ticari ekosistemde buluşturuyoruz.', cta: 'Sırbistan Tedarik Teklifi Al' },
    'macedonia': { slug: 'makedonya', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Kuzey Makedonya Pazarı: Stratejik Ticaret Köprüsü.', description: 'Kuzey Makedonya pazarına tekstil, yapı malzemeleri ve gıda ihracatında operasyonel mükemmellik.', lead: 'Üsküp merkezli operasyonlara ve Kuzey Makedonya pazarındaki tüm alıcılara rekabetçi fiyatlar ve yapılandırılmış ticaret imkanları sunuyoruz.', heading2: 'Kuzey Makedonya İçin Etkin Lojistik', body2: 'Gümrük, menşe belgeleri ve yerel pazar gereksinimlerine tam uyum ile sorunsuz B2B tedarik yönetimi.', cta: 'Makedonya Tedarik Teklifi Al' },""",
    'en': """    'albania': { slug: 'albania', eyebrow: 'Balkans Sourcing & Supply', title: 'Albania Market: Reliable B2B Sourcing from Turkey.', description: 'Uninterrupted supply chain for construction materials, food, and industrial products to the Albanian market.', lead: 'We provide strategic product sourcing from Turkey to projects and wholesalers in Albania with fast logistics.', heading2: 'Direct Solutions for Tirana and Beyond', body2: 'Leveraging our geographical proximity, we manage flexible, fast, and reliable B2B export operations to Albania.', cta: 'Request Supply for Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Balkans Sourcing & Supply', title: 'Serbia Market: B2B Export and Trade Coordination.', description: 'Sourcing industrial raw materials, flat glass, and food from Turkey to Serbia.', lead: 'We offer high-standard strategic sourcing solutions from Turkey to manufacturing facilities and importers in Belgrade and beyond.', heading2: 'A Strong Bridge for Serbian Industry', body2: 'Connecting buyers in Serbia with verified Turkish manufacturers in a highly efficient commercial ecosystem.', cta: 'Request Supply for Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Balkans Sourcing & Supply', title: 'North Macedonia Market: Strategic Trade Bridge.', description: 'Operational excellence in exporting textiles, building materials, and food to North Macedonia.', lead: 'We offer competitive pricing and structured trade opportunities for Skopje-based operations and all buyers in North Macedonia.', heading2: 'Efficient Logistics for North Macedonia', body2: 'Seamless B2B supply management with full compliance to customs, certificates of origin, and local market requirements.', cta: 'Request Supply for Macedonia' },""",
    'de': """    'albania': { slug: 'albanien', eyebrow: 'Balkan-Beschaffung', title: 'Albanien: Zuverlässige B2B-Beschaffung aus der Türkei.', description: 'Beschaffung von Baumaterialien und Industrieprodukten für den albanischen Markt.', lead: 'Wir bieten strategische Produktbeschaffung aus der Türkei für Projekte und Großhändler in Albanien.', heading2: 'Lösungen für Albanien', body2: 'Dank unserer geografischen Nähe steuern wir flexible und schnelle B2B-Exportgeschäfte.', cta: 'Angebot für Albanien anfordern' },
    'serbia': { slug: 'serbien', eyebrow: 'Balkan-Beschaffung', title: 'Serbien: B2B-Export und Handelskoordination.', description: 'Beschaffung von industriellen Rohstoffen und Glas aus der Türkei nach Serbien.', lead: 'Wir bieten Produktionsstätten in Serbien hochwertige strategische Beschaffungslösungen aus der Türkei.', heading2: 'Eine starke Brücke für die serbische Industrie', body2: 'Verbindung serbischer Käufer mit verifizierten türkischen Herstellern.', cta: 'Angebot für Serbien anfordern' },
    'macedonia': { slug: 'mazedonien', eyebrow: 'Balkan-Beschaffung', title: 'Nordmazedonien: Strategische Handelsbrücke.', description: 'Export von Textilien und Baumaterialien nach Nordmazedonien.', lead: 'Strukturierte Handelsmöglichkeiten für Käufer in Nordmazedonien.', heading2: 'Effiziente Logistik für Nordmazedonien', body2: 'Reibungsloses B2B-Versorgungsmanagement unter Einhaltung lokaler Anforderungen.', cta: 'Angebot für Mazedonien anfordern' },""",
    'it': """    'albania': { slug: 'albania', eyebrow: 'Sourcing Balcani', title: 'Mercato Albania: Sourcing B2B affidabile dalla Turchia.', description: 'Fornitura di materiali da costruzione e prodotti industriali per l\\'Albania.', lead: 'Forniamo prodotti strategici dalla Turchia a progetti e grossisti in Albania.', heading2: 'Soluzioni per l\\'Albania', body2: 'Sfruttando la vicinanza, gestiamo operazioni di esportazione B2B flessibili e veloci.', cta: 'Richiedi per l\\'Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Sourcing Balcani', title: 'Mercato Serbia: Export B2B e Coordinamento Commerciale.', description: 'Sourcing di materie prime industriali e vetro dalla Turchia alla Serbia.', lead: 'Offriamo soluzioni di approvvigionamento strategico per le industrie in Serbia.', heading2: 'Un ponte per l\\'industria serba', body2: 'Mettiamo in contatto acquirenti serbi con produttori turchi verificati.', cta: 'Richiedi per la Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Sourcing Balcani', title: 'Macedonia del Nord: Ponte Commerciale Strategico.', description: 'Esportazione di tessili e materiali da costruzione in Macedonia del Nord.', lead: 'Offriamo opportunità di commercio strutturato per gli acquirenti in Macedonia del Nord.', heading2: 'Logistica efficiente per la Macedonia del Nord', body2: 'Gestione della fornitura B2B con piena conformità ai requisiti locali.', cta: 'Richiedi per la Macedonia' },""",
    'ru': """    'albania': { slug: 'albania', eyebrow: 'Поставки на Балканы', title: 'Рынок Албании: Надежные B2B-поставки из Турции.', description: 'Бесперебойная цепочка поставок строительных материалов и промышленных товаров.', lead: 'Мы обеспечиваем стратегические поставки из Турции для проектов в Албании.', heading2: 'Прямые решения для Албании', body2: 'Используя географическую близость, мы управляем гибкими экспортными операциями.', cta: 'Запрос поставок для Албании' },
    'serbia': { slug: 'serbia', eyebrow: 'Поставки на Балканы', title: 'Рынок Сербии: B2B-экспорт и координация.', description: 'Поставки промышленного сырья и стекла из Турции в Сербию.', lead: 'Мы предлагаем стратегические решения по снабжению для промышленных предприятий Сербии.', heading2: 'Мост для сербской промышленности', body2: 'Связываем покупателей в Сербии с проверенными турецкими производителями.', cta: 'Запрос поставок для Сербии' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Поставки на Балканы', title: 'Северная Македония: Стратегический торговый мост.', description: 'Экспорт текстиля и стройматериалов в Северную Македонию.', lead: 'Структурированные торговые возможности для покупателей в Северной Македонии.', heading2: 'Эффективная логистика', body2: 'Бесперебойное управление B2B-поставками с соблюдением местных требований.', cta: 'Запрос поставок для Македонии' },""",
    'fa': """    'albania': { slug: 'albania', eyebrow: 'تأمین بالکان', title: 'بازار آلبانی: تأمین معتبر B2B.', description: 'تأمین مصالح ساختمانی و محصولات صنعتی برای بازار آلبانی.', lead: 'ما تأمین استراتژیک از ترکیه را برای پروژه‌های آلبانی فراهم می‌کنیم.', heading2: 'راه‌حل‌های مستقیم', body2: 'با استفاده از نزدیکی جغرافیایی، عملیات صادرات B2B سریع را مدیریت می‌کنیم.', cta: 'درخواست برای آلبانی' },
    'serbia': { slug: 'serbia', eyebrow: 'تأمین بالکان', title: 'بازار صربستان: صادرات B2B و هماهنگی تجاری.', description: 'تأمین مواد اولیه صنعتی و شیشه برای صربستان.', lead: 'راه‌حل‌های تأمین استراتژیک با استاندارد بالا برای صنایع صربستان.', heading2: 'پل ارتباطی صنعت صربستان', body2: 'اتصال خریداران صربستانی به تولیدکنندگان تایید شده.', cta: 'درخواست برای صربستان' },
    'macedonia': { slug: 'macedonia', eyebrow: 'تأمین بالکان', title: 'مقدونیه شمالی: پل تجاری استراتژیک.', description: 'صادرات منسوجات و مصالح ساختمانی به مقدونیه شمالی.', lead: 'فرصت‌های تجارت ساخت‌یافته برای خریداران در مقدونیه شمالی.', heading2: 'لجستیک کارآمد', body2: 'مدیریت بی‌وقفه تأمین B2B با رعایت الزامات محلی.', cta: 'درخواست برای مقدونیه' },""",
    'zh': """    'albania': { slug: 'albania', eyebrow: '巴尔干采购', title: '阿尔巴尼亚市场：来自土耳其的可靠B2B采购。', description: '为阿尔巴尼亚市场提供建筑材料和工业产品的供应链。', lead: '我们为阿尔巴尼亚的项目和批发商提供来自土耳其的战略采购。', heading2: '直接解决方案', body2: '利用地理优势，我们管理灵活、快速的B2B出口业务。', cta: '阿尔巴尼亚采购请求' },
    'serbia': { slug: 'serbia', eyebrow: '巴尔干采购', title: '塞尔维亚市场：B2B出口和贸易协调。', description: '从土耳其向塞尔维亚采购工业原材料和玻璃。', lead: '我们为贝尔格莱德及其他地区的制造工厂提供高标准的战略采购解决方案。', heading2: '塞尔维亚工业的强大桥梁', body2: '将塞尔维亚的买家与经过验证的土耳其制造商联系起来。', cta: '塞尔维亚采购请求' },
    'macedonia': { slug: 'macedonia', eyebrow: '巴尔干采购', title: '北马其顿市场：战略贸易桥梁。', description: '向北马其顿出口纺织品和建筑材料。', lead: '我们为北马其顿的买家提供结构化的贸易机会。', heading2: '高效物流', body2: '完全遵守当地市场要求的无缝B2B供应管理。', cta: '马其顿采购请求' },""",
    'vi': """    'albania': { slug: 'albania', eyebrow: 'Nguồn cung Balkan', title: 'Thị trường Albania: Nguồn cung B2B đáng tin cậy.', description: 'Chuỗi cung ứng vật liệu xây dựng và sản phẩm công nghiệp cho Albania.', lead: 'Chúng tôi cung cấp nguồn sản phẩm chiến lược từ Thổ Nhĩ Kỳ cho các dự án tại Albania.', heading2: 'Giải pháp trực tiếp', body2: 'Tận dụng lợi thế vị trí, chúng tôi quản lý các hoạt động xuất khẩu B2B nhanh chóng.', cta: 'Yêu cầu cho Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Nguồn cung Balkan', title: 'Thị trường Serbia: Xuất khẩu B2B và Điều phối.', description: 'Tìm nguồn cung nguyên liệu thô công nghiệp và kính cho Serbia.', lead: 'Chúng tôi cung cấp các giải pháp tìm nguồn cung chiến lược cho ngành công nghiệp Serbia.', heading2: 'Cầu nối cho Công nghiệp Serbia', body2: 'Kết nối người mua ở Serbia với các nhà sản xuất Thổ Nhĩ Kỳ đã được xác minh.', cta: 'Yêu cầu cho Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Nguồn cung Balkan', title: 'Bắc Macedonia: Cầu nối Thương mại Chiến lược.', description: 'Xuất khẩu hàng dệt may và vật liệu xây dựng sang Bắc Macedonia.', lead: 'Cơ hội thương mại có cấu trúc cho người mua ở Bắc Macedonia.', heading2: 'Logistics hiệu quả', body2: 'Quản lý cung ứng B2B liền mạch tuân thủ các yêu cầu địa phương.', cta: 'Yêu cầu cho Macedonia' },"""
}

for lang, block in balkans.items():
    pattern = rf"({lang}:\s*{{)"
    content = re.sub(pattern, r"\g<1>\n" + block, content, count=1)

with open('src/data/trade-markets.ts', 'w', encoding='utf-8') as f:
    f.write(content)
print("Done patching balkans.")
