const fs = require('fs');
let content = fs.readFileSync('src/data/trade-markets.ts', 'utf8');

const balkans = {
  'tr': `    'albania': { slug: 'arnavutluk', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Arnavutluk Pazarı: Güvenilir Tedarik ve Lojistik.', description: 'Arnavutluk pazarına yönelik yapı malzemeleri, gıda ve endüstriyel ürünlerde kesintisiz tedarik zinciri.', lead: 'Arnavutluk\\'taki projelere ve toptancılara Türkiye üzerinden stratejik ürün tedariki sağlıyoruz.', heading2: 'Tiran ve Tüm Arnavutluk İçin Doğrudan Çözümler', body2: 'Mesafe avantajını kullanarak Arnavutluk pazarına esnek, hızlı ve güvenilir B2B ihracat operasyonları yönetiyoruz.', cta: 'Arnavutluk Tedarik Teklifi Al' },
    'serbia': { slug: 'sirbistan', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Sırbistan Pazarı: B2B İhracat ve Tedarik.', description: 'Sırbistan için endüstriyel hammadde ve tarımsal ürün tedariki.', lead: 'Sırbistan sanayisi için stratejik tedarik çözümleri ve doğrudan ihracat yönetimi sunuyoruz.', heading2: 'Sırp Sanayisi İçin Tedarik Köprüsü', body2: 'Sırbistan\\'daki alıcıları doğrudan onaylı Türk üreticilerle buluşturarak kesintisiz lojistik sağlıyoruz.', cta: 'Sırbistan Tedarik Teklifi Al' },
    'macedonia': { slug: 'makedonya', eyebrow: 'Balkanlar İhracat & Tedarik', title: 'Kuzey Makedonya: Stratejik Ticaret Köprüsü.', description: 'Kuzey Makedonya\\'ya tekstil, ambalaj ve yapı malzemeleri ihracatı.', lead: 'Kuzey Makedonya\\'daki alıcılar için yapılandırılmış, güvenli ve düzenli ticaret fırsatları.', heading2: 'Kuzey Makedonya İçin Hızlı Lojistik', body2: 'Yerel gereksinimlere tam uyumlu B2B tedarik yönetimi.', cta: 'Makedonya Tedarik Teklifi Al' },`,
  'en': `    'albania': { slug: 'albania', eyebrow: 'Balkans Sourcing', title: 'Albania Market: Reliable B2B Sourcing.', description: 'Seamless supply chain of construction materials and industrial products to Albania.', lead: 'We provide strategic product sourcing from Türkiye to projects and wholesalers in Albania.', heading2: 'Direct Solutions for Albania', body2: 'Leveraging proximity, we manage flexible and compliant B2B export operations.', cta: 'Request for Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Balkans Sourcing', title: 'Serbia Market: B2B Export and Coordination.', description: 'Sourcing industrial raw materials and commodities for Serbia.', lead: 'We offer strategic sourcing solutions and direct export management for the Serbian industry.', heading2: 'Supply Bridge for Serbian Industry', body2: 'Connecting buyers in Serbia directly with verified Turkish manufacturers.', cta: 'Request for Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Balkans Sourcing', title: 'North Macedonia: Strategic Trade Bridge.', description: 'Exporting textiles and construction materials to North Macedonia.', lead: 'Structured trade opportunities for buyers in North Macedonia.', heading2: 'Efficient Logistics', body2: 'Seamless B2B supply management fully compliant with local requirements.', cta: 'Request for Macedonia' },`,
  'de': `    'albania': { slug: 'albanien', eyebrow: 'Balkan-Beschaffung', title: 'Markt Albanien: Zuverlässige B2B-Beschaffung.', description: 'Lieferkette für Baumaterialien und Industrieprodukte nach Albanien.', lead: 'Wir bieten strategische Produktbeschaffung aus der Türkei für Projekte und Großhändler in Albanien.', heading2: 'Direkte Lösungen für Albanien', body2: 'Unter Ausnutzung der geografischen Nähe verwalten wir flexible Exportgeschäfte.', cta: 'Anfrage für Albanien' },
    'serbia': { slug: 'serbien', eyebrow: 'Balkan-Beschaffung', title: 'Markt Serbien: B2B-Export und Koordination.', description: 'Beschaffung von industriellen Rohstoffen für Serbien.', lead: 'Wir bieten strategische Beschaffungslösungen für die serbische Industrie.', heading2: 'Lieferbrücke für die serbische Industrie', body2: 'Verbindung von Käufern in Serbien mit verifizierten türkischen Herstellern.', cta: 'Anfrage für Serbien' },
    'macedonia': { slug: 'mazedonien', eyebrow: 'Balkan-Beschaffung', title: 'Nordmazedonien: Strategische Handelsbrücke.', description: 'Export von Textilien und Baumaterialien nach Nordmazedonien.', lead: 'Strukturierte Handelsmöglichkeiten für Käufer in Nordmazedonien.', heading2: 'Effiziente Logistik', body2: 'Reibungsloses B2B-Liefermanagement unter Einhaltung lokaler Vorschriften.', cta: 'Anfrage für Mazedonien' },`,
  'it': `    'albania': { slug: 'albania', eyebrow: 'Sourcing Balcani', title: 'Mercato Albania: Sourcing B2B Affidabile.', description: 'Catena di approvvigionamento di materiali da costruzione per l\\'Albania.', lead: 'Forniamo sourcing strategico di prodotti dalla Turchia a progetti e grossisti in Albania.', heading2: 'Soluzioni dirette per l\\'Albania', body2: 'Sfruttando la vicinanza, gestiamo operazioni di esportazione flessibili.', cta: 'Richiedi per l\\'Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Sourcing Balcani', title: 'Mercato Serbia: Esportazione e Coordinamento B2B.', description: 'Approvvigionamento di materie prime industriali per la Serbia.', lead: 'Offriamo soluzioni di sourcing strategico per l\\'industria serba.', heading2: 'Ponte di fornitura per l\\'industria serba', body2: 'Colleghiamo gli acquirenti in Serbia direttamente con produttori turchi verificati.', cta: 'Richiedi per la Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Sourcing Balcani', title: 'Macedonia del Nord: Ponte Commerciale Strategico.', description: 'Esportazione di tessili e materiali da costruzione in Macedonia del Nord.', lead: 'Offriamo opportunità di commercio strutturato per gli acquirenti in Macedonia del Nord.', heading2: 'Logistica efficiente per la Macedonia del Nord', body2: 'Gestione della fornitura B2B con piena conformità ai requisiti locali.', cta: 'Richiedi per la Macedonia' },`,
  'ru': `    'albania': { slug: 'albania', eyebrow: 'Поставки на Балканы', title: 'Рынок Албании: Надежные B2B-поставки.', description: 'Бесперебойная цепочка поставок строительных материалов.', lead: 'Мы обеспечиваем стратегические поставки из Турции для проектов и оптовиков.', heading2: 'Прямые решения для Албании', body2: 'Используя близость, мы управляем гибкими экспортными операциями.', cta: 'Запрос для Албании' },
    'serbia': { slug: 'serbia', eyebrow: 'Поставки на Балканы', title: 'Рынок Сербии: B2B-экспорт и координация.', description: 'Поставки промышленного сырья для Сербии.', lead: 'Мы предлагаем стратегические решения по поставкам для сербской промышленности.', heading2: 'Мост поставок для Сербии', body2: 'Связываем покупателей в Сербии с проверенными турецкими производителями.', cta: 'Запрос для Сербии' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Поставки на Балканы', title: 'Северная Македония: Торговый мост.', description: 'Экспорт текстиля и строительных материалов.', lead: 'Структурированные торговые возможности для покупателей в Северной Македонии.', heading2: 'Эффективная логистика', body2: 'Бесперебойное управление B2B-поставками.', cta: 'Запрос для Македонии' },`,
  'fa': `    'albania': { slug: 'albania', eyebrow: 'تأمین بالکان', title: 'بازار آلبانی: تأمین B2B.', description: 'تأمین مصالح ساختمانی و صنعتی برای آلبانی.', lead: 'ما تأمین استراتژیک از ترکیه را برای پروژه‌ها در آلبانی ارائه می‌دهیم.', heading2: 'راه‌حل‌های مستقیم برای آلبانی', body2: 'عملیات صادراتی B2B با تکیه بر نزدیکی جغرافیایی.', cta: 'درخواست برای آلبانی' },
    'serbia': { slug: 'serbia', eyebrow: 'تأمین بالکان', title: 'بازار صربستان: صادرات و تأمین.', description: 'تأمین مواد اولیه صنعتی برای صربستان.', lead: 'راه‌حل‌های استراتژیک برای صنایع صربستان.', heading2: 'پل تأمین برای صربستان', body2: 'ارتباط مستقیم خریداران با تولیدکنندگان معتبر.', cta: 'درخواست برای صربستان' },
    'macedonia': { slug: 'macedonia', eyebrow: 'تأمین بالکان', title: 'مقدونیه شمالی: پل تجاری استراتژیک.', description: 'صادرات منسوجات و مصالح ساختمانی.', lead: 'فرصت‌های تجاری ساختاریافته برای مقدونیه.', heading2: 'لجستیک کارآمد', body2: 'مدیریت زنجیره تأمین B2B.', cta: 'درخواست برای مقدونیه' },`,
  'zh': `    'albania': { slug: 'albania', eyebrow: '巴尔干采购', title: '阿尔巴尼亚市场：可靠的B2B采购', description: '为阿尔巴尼亚提供无缝的建筑和工业材料供应链。', lead: '我们为阿尔巴尼亚的项目提供土耳其的战略采购。', heading2: '直接解决方案', body2: '利用地理位置优势管理出口。', cta: '阿尔巴尼亚询价' },
    'serbia': { slug: 'serbia', eyebrow: '巴尔干采购', title: '塞尔维亚市场：B2B出口和采购。', description: '为塞尔维亚采购工业原材料。', lead: '我们为塞尔维亚工业提供战略采购解决方案。', heading2: '塞尔维亚的供应桥梁', body2: '将买家直接与土耳其制造商连接。', cta: '塞尔维亚询价' },
    'macedonia': { slug: 'macedonia', eyebrow: '巴尔干采购', title: '北马其顿：战略贸易桥梁。', description: '向北马其顿出口纺织品和建筑材料。', lead: '为北马其顿买家提供结构化的贸易机会。', heading2: '高效物流', body2: '遵守当地要求的无缝B2B供应管理。', cta: '马其顿询价' },`,
  'vi': `    'albania': { slug: 'albania', eyebrow: 'Nguồn cung Balkan', title: 'Thị trường Albania: Nguồn cung B2B đáng tin cậy.', description: 'Chuỗi cung ứng vật liệu xây dựng và sản phẩm công nghiệp cho Albania.', lead: 'Chúng tôi cung cấp nguồn sản phẩm chiến lược từ Thổ Nhĩ Kỳ cho các dự án tại Albania.', heading2: 'Giải pháp trực tiếp', body2: 'Tận dụng lợi thế vị trí, chúng tôi quản lý các hoạt động xuất khẩu B2B nhanh chóng.', cta: 'Yêu cầu cho Albania' },
    'serbia': { slug: 'serbia', eyebrow: 'Nguồn cung Balkan', title: 'Thị trường Serbia: Xuất khẩu B2B và Điều phối.', description: 'Tìm nguồn cung nguyên liệu thô công nghiệp và kênh cho Serbia.', lead: 'Chúng tôi cung cấp các giải pháp tìm nguồn cung chiến lược cho ngành công nghiệp Serbia.', heading2: 'Cầu nối cho Công nghiệp Serbia', body2: 'Kết nối người mua ở Serbia với các nhà sản xuất Thổ Nhĩ Kỳ đã được xác minh.', cta: 'Yêu cầu cho Serbia' },
    'macedonia': { slug: 'macedonia', eyebrow: 'Nguồn cung Balkan', title: 'Bắc Macedonia: Cầu nối Thương mại Chiến lược.', description: 'Xuất khẩu hàng dệt may và vật liệu xây dựng sang Bắc Macedonia.', lead: 'Cơ hội thương mại có cấu trúc cho người mua ở Bắc Macedonia.', heading2: 'Logistics hiệu quả', body2: 'Quản lý cung ứng B2B liền mạch tuân thủ các yêu cầu địa phương.', cta: 'Yêu cầu cho Macedonia' },`
};

for (const [lang, block] of Object.entries(balkans)) {
  const findRegex = new RegExp('(' + lang + ':\\s*\\{)');
  content = content.replace(findRegex, "$1\n" + block);
}

fs.writeFileSync('src/data/trade-markets.ts', content, 'utf8');
console.log('Done');
